### ISSUE TITLE
Newline format is missing carriage return

### ISSUE THREAD

**Issue by tennox** [bendrucker/mailto-link#3]
According to RFC newlines should be represented by `%0D%0A` not only `%0A`:
https://stackoverflow.com/questions/10356329/mailto-link-multiple-body-lines

**Comment by tennox** [comment]
But then again, 2 out of 3 email clients I've tried (Mailspring and Spark android app) will produce additional newlines if you do so.

Maybe I don't want this after all :P

**Comment by bendrucker** [comment]
Tried this out on iOS 14.5 and got identical results with and without the carriage return on both Apple Mail and Spark. The mentioned RFC is from 2010, so it's not surprising that implementations aren't faithful to any new requirements/clarifications there. Apple's docs link to the 1998 original:

https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MailLinks/MailLinks.html

It's easy to `body.replace('\n', '\r\n')` currently. But if the library does that, it would also need a flag to permit opt out, which I'm not particularly keen on adding.

Gmail is perpetually breaking things and is not going to obey newlines reliably:

https://stackoverflow.com/a/62795673

Have you spotted any clients that only handle `\r\n`? Happy to adhere to the spec if some clients require it knowing that newlines are inherently unreliable and whitespace will differ from app to app.

**Comment by tennox** [comment]
I actually encountered opposite results. (opposite to what Stackoverflow suggests):
Spark for Android and Mailspring on Linux will both add extra newlines when using carriage return.

As I have not yet encountered a case where a carriage return was needed, I would agree with your proposal and keep it as is. :thumbs_up:
